### ISSUE TITLE
`File: Delete` sometimes closes a second tab

### ISSUE THREAD

**Issue by garyking** [sleistner/vscode-fileutils#137]
**Describe the bug**

Run `File: Delete` on a file, with two files open. Sometimes, the file will get deleted, and the second one gets closed. This started happening a few days ago.

**To Reproduce**

1. Run `File: Delete` on a file, with at least two files open.
2. The active file gets deleted, then the second file gets closed. This happens about 30% of the time.

**Expected behavior**

The second file should be active after the deletion of the first file, but not closed.

**Desktop (please complete the following information):**

- VSCode Version: Version: 1.37.1
- OS Version: MacOS 10.14.6 (18G87)

**Comment by sleistner** [comment]
Thank you for the report @garyking. I narrowed the problem down and it seems `workspace.fs.delete(...)` which is now used instead of `fs-extra`, also closes the tab of the deleted file.
The (API Documentation)[https://code.visualstudio.com/api/references/vscode-api#FileSystem] does not mentioned such behaviour.
The fix is rather simple but I want to verify first if the above described behaviour is desired from VS Code API and stable.
