### ISSUE TITLE
Ability to make file add prompt begin from project root instead of computer root

### ISSUE THREAD

**Issue by parssak** [sleistner/vscode-fileutils#485]
**Is your feature request related to a problem? Please describe.**
Super annoying to create files relatives to folder because the file name prompt is half taken up by the path of where my project is, instead of starting at the project root.

**Describe the solution you'd like**
A setting so that the path for where I want to add the file begins at the project root instead of my computer root.

**Describe alternatives you've considered**
There are no settings exposed to be able to do this that I could find

**Additional context**
<img width="512" alt="image" src="https://user-images.githubusercontent.com/33424333/207908288-4b0c3356-f593-4fd0-94ea-8e82e076c702.png">

**Comment by sleistner** [comment]
Hi @parssak thanks for reaching out. 
Did you have a look at the `fileutils.typeahead.enabled` setting?

If set to `true` a prompt showing a tree structure should pop up.
<img width="636" alt="Screenshot 2022-12-19 at 11 50 36" src="https://user-images.githubusercontent.com/12568/208409483-c050ee8f-26f8-4cd8-b867-c3dce0003435.png">

Let me know if that would serve your purpose, otherwise we could consider your proposed change.

**Comment by parssak** [comment]
Yeah I looked into it, however when i go to write my filename it's still mostly covered by the path, would really appreciate the change!

<img width="678" alt="image" src="https://user-images.githubusercontent.com/33424333/209406972-7b7672da-9fa6-48a8-9d04-42eaa4326978.png">

**Comment by parssak** [comment]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/33424333/217636813-bd594ab4-8742-4f05-9481-f8cf1d76286c.png">

tysm! 🙌🏻🙌🏻
