### ISSUE TITLE
What's up with the 3.5.2 release?

### ISSUE THREAD

**Issue by F30** [sleistner/vscode-fileutils#500]
The Extension Marketplace currently contains version 3.5.2 and so VScode suggests to update to it. It has been created on the same day as version 3.5.1, 2023-01-11.

However, I can find no indication of that release here in the repository: "package.json" still contains 3.5.0 and no new [release](https://github.com/sleistner/vscode-fileutils/releases) has been created. This left me wondering and worried about a malicious takeover.

I ran a quick diff between the extension contents of 3.5.0 and 3.5.2 and at least couldn't find anything malicious. The major difference, apart from some metadata changes, appears to be a ton of more bundled NPM packages.

It would be great if you could clarify things and confirm that 3.5.2 is a legit release.

**Comment by sleistner** [comment]
Hi @F30, no need to worry, I had to restore a previous version as a quick fix because version `3.5.1` did not work as expected (failing due to various issues regarding VSCode api and packages), even though local execution and tests indicated otherwise.
I need to have a deeper look at it and understand the recent VSCode api changes better.

Sorry for the confusion.

**Comment by F30** [comment]
Alright, thanks for your reply!
